# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-27 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemicanvas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
