# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-04 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemicanvas', '0002_auto_20170604_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
