# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-30 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemicanvas', '0002_artist_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributions',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contributions',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
