# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-03 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemicanvas', '0002_auto_20170603_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
