# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-04 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemicanvas', '0003_auto_20170604_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='image',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
