# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-30 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epidemicanvas', '0003_auto_20170530_1008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributions',
            options={'verbose_name': 'Contribution', 'verbose_name_plural': 'Contributions'},
        ),
    ]
