# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-04 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemicanvas', '0004_auto_20170604_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='picture',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
