# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-04 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epidemicanvas', '0005_artist_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('startX', models.IntegerField(default=0)),
                ('startY', models.IntegerField(default=0)),
                ('endX', models.IntegerField(default=0)),
                ('endY', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epidemicanvas.Artist')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epidemicanvas.Session')),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
            },
        ),
    ]
