# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-05 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemicanvas', '0006_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='color',
            field=models.CharField(default='#0f0f0f', max_length=50),
        ),
        migrations.AddField(
            model_name='action',
            name='size',
            field=models.IntegerField(default=1),
        ),
    ]
